scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['http://35.240.130.147']
        labels:
          application: 'PenjualanPembelianApplication'